---
title: "Lista - AP2 - Identificação e Modelagem de Processos Estacionários"
author: "Jessé Peixoto de Freitas"
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
output: html_document
---

## Questão 1:

Calcule as FAC e FACP (5 primeiros valores) para os processos estacionários a seguir:
        
  a. $Y_t = \varepsilon _t + \theta \varepsilon_{t-1}; \theta = -0,5$
  
  b. $(1 - \phi L )Y_t = \varepsilon _t; \phi = -0,9$
  
  c. $(1 - \phi L )Y_t = \varepsilon _t + \theta \varepsilon_{t-1} ; \phi = -0,9 ; \theta = -0,5; $
  
## Questão 2:

Obtenha as Séries do IPCA (IBGE), Saldo de Crédito Total (BCB), Retornos do
Ibovespa e o preço de um ativo presente na B3 à sua escolha. (Todas mensais, de
01/2015 a 12/2022). Então, para cada série:

  a. Realize os testes de identificação, assim como os de Critério de Informação e
Diagnóstico de Resíduos.

  b. Plote os gráficos de FAC e FACP.

  c. Estime os coeficientes e apresente os modelos. (Utilize software apropriado)

  d. O preço do ativo pode ser modelado por um processo estacionário? Se não,
justifique e verifique se o retorno desse ativo é um processo estacionário.

## Questão 3: 

Utilizando as séries disponibilizadas no arquivo "AP2.xlsx", faça para cada uma das séries o que se pede:

a. Realize os testes de identificação, assim como os de Critério de Informação e
Diagnóstico de Resíduos.

b. Plote os gráficos de FAC e FACP.

c. Estime os coeficientes e apresente os modelos. (Utilize software apropriado)
